server:
  port: 8081
spring:
  application:
    name: sw-mianshi
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mianshi?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1111
  redis:
    host: 222.79.104.69
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    password: redispass123
    database: 0
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
logging:
  level:
    com.snwolf: debug